[package]
name = "mandelbrot"
version = "0.2.0"
authors = ["Jim Blandy <jimb@red-bean.com>"]
edition = "2018"

[dependencies]
num = "0.4"
image = "0.13.0"
crossbeam = "0.2.9"
atomic_chunks_mut = { git = "https://github.com/jimblandy/atomic-chunks-mut.git" }
measurement = {path = "../measurement"}